version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    container_name: prisma-zenstack-rest-gen-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prisma_rest_gen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   container_name: zenstack-app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/zenstack_db
  #   depends_on:
  #     - db
  #   command: pnpm start

volumes:
  postgres_data:
